### ISSUE TITLE
wrong label in background rate figure

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/pyirf#117]
Hi
I think the ylabel unit is wrong in the background rate figure in the [comparison with EventDisplay](https://cta-observatory.github.io/pyirf/notebooks/comparison_with_EventDisplay.html).
It should be `1/s` (or `Hz`) and not `1/(s.TeV)` no?

**Comment by HealthyPear** [comment]
the label corresponds to what we are doing, i.e background rate per energy, observation time (and technically per solid angle, but we only 1 bin so far since we only used on-axis data)

even though now that I look better, in the IRF report the background rate is reported as integrated in the energy bin

**Comment by vuillaut** [comment]
It does not seem to be "per energy" (but as a function of energy), the code reads
```
rate_bin.to_value(1 / u.s)
```
and the plot and values are consistent with [CTA background rate in `Hz`](https://portal.cta-observatory.org/cta_observatory/performance/SitePages/Home.aspx).

**Comment by maxnoe** [comment]
@vuillaut Yes, you are right, the rate displayed is only `s⁻¹`, the label is a left over from before where we normalized EventDisplay to the GADF definition instead of the other way around.
