### ISSUE TITLE
Current ctapipe reference version 0.7 ?

### ISSUE THREAD

**Issue by bregeon** [cta-observatory/pyirf#19]
I have just noticed that the environment file has `ctapipe == 0.7`
Could that easily become `>=0.7` or even `== 0.8` that is the latest release?

ps: I have made no test :)

**Comment by MaxNoe** [comment]
Why do we need ctapipe here at all?

**Comment by vuillaut** [comment]
ctapipe is a "loose" requirement.
At the end it could be completely independent of it, we just use some nice functions to read files, etc... 
so shot answer: yes it could

**Comment by bregeon** [comment]
From my point of view, pyIRF is for CTA, and could/should use as much as possible ctapipe I/O, plotting capabilities, "cut" implementations.

**Comment by HealthyPear** [comment]
I think both are good points.

From one side, we are in a very good position.
When PR #12 will be in place you will see that reading DL2 data (limiting file-formats to FITS & HDF5) from _**any**_ facility requires from our side only to hard-code the structure of the file (basically the tables).
The nomenclature of the variables is left to the user.
The final output format will be the same for every experiment/observatory, so it will be easy to e.g. superimpose IRFs and sensitivity curves.

On the other side, re-inventing the wheel sometimes is not convenient, so I guess that if we _really_ need something from ctapipe we can use it as an optional and properly cited dependence/reference.
Personally I don't think I/O or plotting code is too much of a problem because _pyirf_ has fewer degrees of freedom than _ctapipe/protopipe_ .
The only thing that comes to my mind is perhaps more complex and useful classes like `ctapipe.core.Tool` ...

**Comment by MaxNoe** [comment]
@bregeon Actually, I don't think there is anything we *need* for this here in ctapipe.

If there are certain parts that we also want to use here that are more general, it would make more sense to extract those from ctapipe and put them into their own modules to allow for leaner dependency trees.

**Comment by bregeon** [comment]
@MaxNoe ok, I agree, I think when I write `ctapipe` I really mean the full eco-system rather than just the module in itself.

**Comment by HealthyPear** [comment]
I will close this for the time being, since for the time being there is no need to import ctapipe.
