### ISSUE TITLE
pytables vs panda for i/o

### ISSUE THREAD

**Issue by bregeon** [cta-observatory/pyirf#32]
This module uses `panda` to read the DL2 input files.
Sounds like `pytable` is to be preferred to read DL1 files.
I know that knowledgeable people use indifferently `pytables`, `panda` and `h5py`according to their needs, but having one consistent preference across the pipelines is good for less knowledgeable people.

I would propose if possible to move to `pytables` possibly until there exist a ctapipe DL2 event source.

**Comment by bregeon** [comment]
Side comment the environment file of this project has a dependency over `pytables` although it's never used.

**Comment by MaxNoe** [comment]
> has a dependency over pytables although it's never used. 

pytables is an optional dependency of pandas to read hdf files. If you want to read hdf5 using pandas, you need pytables.

> I would propose if possible to move to pytables possibly until there exist a ctapipe DL2 event source.

No. I would go for an entirely different approach.

This library should not be concerned with DL2 io. It should provide functions to calculate IRFs and sensitivity. But that's a discussion for another issue.

What you here propose is not really a question of the io library but a question of the internal data structure we want to use.

That is issue  #28. If we choose pandas, it makes no sense to not use pandas to read the event tables into pandas data frames. If we chose astropy tables, it does not really make sense to use pandas over the lower-level pytables directly.

So I don't think `pandas` vs. `pytables` is actually the question here.

> ctapipe DL2 event source.

I don't think there will ever be one. There is basically no use-case I am aware of for reading DL2 data event wise. Normally, you will want to read whole columns or the whole dataset. Not every column row by row.

**Comment by kosack** [comment]
> exist a ctapipe DL2 event source

There will never be a DL2 event source - at the DL2 and above level, you never need to iterate everywise over the event-list, you can do everything at once using pandas/pytables. Either should work fine.  The main thing to remember is that there is some extra metadata in those files that will be missed by pandas alone (headers, units, etc), so likely in the end you need to use a bit of both, or use astropy.Table instead to retain that info. 

In any case, the preferred method is to read the full event list at once and operate on it, rather than to loop over events. 

I'd suggest in general to use this method, since it retains the units and header metadata:
```py3
import pytables
from astropy.table import Table

h5file = pytables.open_file("events.dl2.h5")
event_list = Table(h5file.root.dl2.events[:]) # dl2 is now an AstroPy Table object
print(event_list['energy'].mean()) # → 14.3 TeV (units are maintained)

# then later if you prefer to use a Pandas function, just do
df = event_list.to_pandas()
df.hist()

```

**Comment by MaxNoe** [comment]
I don't think you example works. How would astropy know the units in this case?

**Comment by kosack** [comment]
> How would astropy know the units in this case?

Sorry, you're right, this should be as follows rather than using pytables to open the file: 

```python
   event_list = Table.read("events.dl2.h5", "/dl2/events")
```

I only used the intermediate pytables → astropy table method to get to tables with *vector* columns, but that is not a problem for DL2 event lists. You can do it directly, but of course it currently uses *h5py* underneath, and there were still some unicode incompatibilities that caused me some issues in the past (not sure in the latest astropy version if this is fixed)

**Comment by MaxNoe** [comment]
This also does currently not work, as we use a different way of storing units with the columns as does astropy. We use a hdf5 attribute, which is a good option I would say, but astropy writes YAML data into a second dataset.

**Comment by kosack** [comment]
(see my edit above, yes)

**Comment by kosack** [comment]
Let's then write a nice helper function to do it right and give back an astropy Table with correct units and headers.

**Comment by kosack** [comment]
see https://github.com/cta-observatory/ctapipe/pull/1427

**Comment by vuillaut** [comment]
Rather than an event source, I think @bregeon (please correct me otherwise) would rather have a `read_dl2_parameters` method or similar in ctapipe than having to know by himself that he has to use pandas or pytable and that the parameters are in that table in the file, etc...

**Comment by vuillaut** [comment]
Edit: ok I see from the last comments that you are going in that direction already

**Comment by kosack** [comment]
Yes, I think in the near future I will try to overhaul all of the data access parts of ctapipe (there is both utils.datasets, and io.*), and make some better helper functions.  For now, the PR listed above should be enough to get going.
