### ISSUE TITLE
Input DL2 format

### ISSUE THREAD

**Issue by HealthyPear** [cta-observatory/pyirf#5]
At the start of the project the DL2 input format was that of [protopipe](https://github.com/cta-observatory/protopipe).
The final format to be read by _pyirf_ should be the one provided by _ctapipe_.

For reference, here are some of the relevant issues/PR present there,
- cta-observatory/ctapipe#173
- cta-observatory/ctapipe#858
- cta-observatory/ctapipe#1165

Of course that work is still ongoing, so this is just an initial direction.

**Comment by HealthyPear** [comment]
Temporary input formats to be supported:

- lstchain (is it already synchronized with ctapipe @vuillaut ?)
- EventDisplay (in order to be able to crosscheck the basic first results - see #2 )
- CTA-MARS ?
- other single telescope data e.g. from NectarCam, ASTRI, ecc?

**Comment by kosack** [comment]
DL2 is fortunately much simpler than DL1, especially since you only need the DL2/Event/Subarray information (a single table with shower + discrimination parameters).  It essentially will looks like the DL3 format, only in HDF5 and with possibly more than one shower reconstruction, so we'll need to think of some conventions for that. 

I'd suggest designing the software similar to how IACT-Tools (or whatever the FACT one is called), where the columns you use as input are just a dict somewhere, so you can easily adapt to different formats.


One question from me: will this package do all of the parts of Stage 3 of the pipeline, or just the IRF parts?   For that I mean, there is a first step to divide events into reconstruction classes and choose which reconstruction to use for each event (if multiple are included at once). It's not clear if that is part of this or not.  If not, then what you really take as input is not DL2/Event, but really DL3/Event (where the final reconstruction has been chosen, event quality classification has been applied, and gamma/hadron discrimination has been applied)

**Comment by HealthyPear** [comment]
> DL2 is fortunately much simpler than DL1, especially since you only need the DL2/Event/Subarray information (a single table with shower + discrimination parameters). It essentially will looks like the DL3 format, only in HDF5 and with possibly more than one shower reconstruction, so we'll need to think of some conventions for that.

If the purpose of pyirf is to be used by CTA **and** other related insturments, it is obvious that there will not be a sigle data format in the end.
Otherwise, the current plan remains unchanged.

> I'd suggest designing the software similar to how IACT-Tools (or whatever the FACT one is called), where the columns you use as input are just a dict somewhere, so you can easily adapt to different formats.

Could you point this to me? I am afraid I am not familiar with it...

**Comment by MaxNoe** [comment]
> If the purpose of pyirf is to be used by CTA and other related insturments, it is obvious that there will not be a sigle data format in the end.

I don't think pyirf should concern itself to much with input file formats.

Provide library functions that take plain arrays of the needed quantities and some example scripts how to use these functions with file format X

**Comment by HealthyPear** [comment]
> I don't think pyirf should concern itself to much with input file formats.
> 
> Provide library functions that take plain arrays of the needed quantities and some example scripts how to use these functions with file format X

But if the same variable in some other DL2 file (not produced with a ctapipe-based pipeline) has a different name, this has to be coded into pyirf no?

> https://github.com/fact-project/aict-tools

Thank you!

**Comment by HealthyPear** [comment]
As per #36, now any specific input format translation to the internal data format of _pyirf_ is left to the specific pipeline which will import _pyirf_ functions.
